### ISSUE TITLE
Error in "map_snps_to_genes"

### ISSUE THREAD

**Issue by LDHHAHA** [neurogenomics/MAGMA_Celltyping#105]
## 1. Bug description
 I had arealdy Munged GWAS data in formatted type, and an error came when i ran the following steps:
genesOutPath <- MAGMA.Celltyping::map_snps_to_genes(path_formatted = path_formatted,
                                                    genome_build = "GRCh37",
						    upstream_kb=10,downstream_kb=1.5,
						    storage_dir = "./ref/MAGMA/")

### Console output 
```
  Cannot access release data for repository neurogenomics/MAGMA_Celltyping. Check that you have provided a .token and that at least one release on your GitHub repository page.		

```
### Expected behaviour   
Any help is greatly appreciated.

**Comment by bschilder** [comment]
Likely related to this issue #102 
Root cause is [piggyback](https://github.com/ropensci/piggyback), working with the developers of that package to try and get it resolved

**Comment by LDHHAHA** [comment]
> 
remotes::install_github("ropensci/piggyback@gh_token")  # done
but the follwing code met another error
piggyback::pb_download(repo="cboettig/piggyback-tests")

Error in match.fun(FUN) : 
  lazy-load database '/share/home/zhangwl/R/x86_64-pc-linux-gnu-library/4.1/piggyback/R/piggyback.rdb' is corrupt
In addition: Warning messages:
1: In match.fun(FUN) : restarting interrupted promise evaluation
2: In match.fun(FUN) : internal error -3 in R_decompress1

**Comment by bschilder** [comment]
> > 
> 
> remotes::install_github("ropensci/piggyback@gh_token") # done but the follwing code met another error piggyback::pb_download(repo="cboettig/piggyback-tests")
> 
> Error in match.fun(FUN) : lazy-load database '/share/home/zhangwl/R/x86_64-pc-linux-gnu-library/4.1/piggyback/R/piggyback.rdb' is corrupt In addition: Warning messages: 1: In match.fun(FUN) : restarting interrupted promise evaluation 2: In match.fun(FUN) : internal error -3 in R_decompress1

Could you please post this Issue on the piggyback repo instead of here? I'm afraid I'm not the maintainer of that package.

**Comment by bschilder** [comment]
in the meantime, I've pushed some checks that give instructions on how to resolve this issue by adding GitHub PAT:
https://github.com/neurogenomics/MAGMA_Celltyping/issues/102#issuecomment-1091528361

**Comment by LDHHAHA** [comment]
> ## 1. Bug description
> I had arealdy Munged GWAS data in formatted type, and an error came when i ran the following steps: genesOutPath <- MAGMA.Celltyping::map_snps_to_genes(path_formatted = path_formatted, genome_build = "GRCh37", upstream_kb=10,downstream_kb=1.5, storage_dir = "./ref/MAGMA/")
> 
> ### Console output
> ```
>   Cannot access release data for repository neurogenomics/MAGMA_Celltyping. Check that you have provided a .token and that at least one release on your GitHub repository page.		
> ```
> 
> ### Expected behaviour
> Any help is greatly appreciated.

Sorry, I am newer to use this software. I met another error when run the above steps:

Error in data.table::fread(tmp, nrows = 10, nThread = 1) : 
  Single column input contains invalid quotes. Self healing only effective when ncol>1

**Comment by bschilder** [comment]
Did you re-install MAGMA.Celltyping and follow the instructions here?
https://github.com/neurogenomics/MAGMA_Celltyping/issues/102#issuecomment-1091528361

**Comment by LDHHAHA** [comment]
> 

Yes, but did not work.

**Comment by bschilder** [comment]
> Error in data.table::fread(tmp, nrows = 10, nThread = 1) : Single column input contains invalid quotes. Self healing only effective when ncol>1

The fact that you got this error suggests you're not using the latest version. The line that this comes from was removed.
Please try re-installing and make sure to restart your R session.
