### ISSUE TITLE
plot_celltype_associations using old 'quantiles' variable

### ISSUE THREAD

**Issue by krademaker** [neurogenomics/MAGMA_Celltyping#11]
Hi,

I was running the 2018 CLOZUK GWAS against the KI dataset, and when trying to plot the cell type associations with I noticed the method still uses the old 'quantiles' variable.

```
# Preparing ctd_allKI dataset
ctd = prepare.quantile.groups(ctd_allKI,
                              specificity_species = 'mouse',
                              numberOfBins = 40)

# Mapping SNPs to genes
scz_genes_out_path = map.snps.to.genes(scz_gwas_sum_stats_path,
                                       genome_ref_path = genome_ref_path)

# Cell type association test
scz_ct_assoc_linear = calculate_celltype_associations(ctd,
                                                      scz_gwas_sum_stats_path,
                                                      genome_ref_path = genome_ref_path,
                                                      specificity_species = 'mouse')

# Plot associations
scz_figs_linear = plot_celltype_associations(scz_ct_assoc_linear,
                                             ctd = ctd)
```
Up until the last step everything works, SNPs are mapped etc., however after the last step this error occurs:
```
Error in t.default(ctd[[annotLevel]]$quantiles) : 
  argument is not a matrix
```
I could circumvent this by changing the names, e.g.:
```
names(ctd[[1]])[names(ctd[[1]]) == "specificity_quantiles"] <- 'quantiles'
names(ctd[[2]])[names(ctd[[2]]) == "specificity_quantiles"] <- 'quantiles'
```
However I think this is just a case of the source code still using an old variable name, can this be updated?

**Comment by MKBakker** [comment]
Hi,
I ran into this one too. The problem comes from `get.ctd.dendro()`
which is called by `plot_celltype_associations()` in the following line:
`ctdDendro = get.ctd.dendro_patch(ctd, annotLevel = annotLevel)`.

Changing `get.ct.denro()` from:
`binned_file_dist <- dist(t(ctd[[annotLevel]]$quantiles))`
to:
`binned_file_dist <- dist(t(ctd[[annotLevel]]$specificity_quantiles))`
solves the problem.

Could this be updated?

**Comment by NathanSkene** [comment]
Hi, my thanks to both of you for spotting this bug and letting me know about it. It should be fixed now.
