### ISSUE TITLE
Checking labelling of "-log10 P-value" on plot x-axis

### ISSUE THREAD

**Issue by krademaker** [neurogenomics/MAGMA_Celltyping#12]
Hi,

If I understand it correctly, association analysis results stores a log10 transformed copy of the P-value in the output file. However, when these P-values are [plotted](https://github.com/NathanSkene/MAGMA_Celltyping/blob/c8f96398438b6c83298075690fa2cb75f3d15d64/R/plot_celltype_associations.r#L63), the x-axis legend indicates '-log10(pvalue)', shouldn't this be 'log10(pvalue)'?

**Comment by bschilder** [comment]
hi @krademaker , sorry this took so long to address. You're correct, there's a mismatch between the label and the axis values. I've made them consistently -log10 in the dev branch (which will be merged soon).
