### ISSUE TITLE
Overadjustment for multiple testing?

### ISSUE THREAD

**Issue by AMCalejandro** [neurogenomics/MAGMA_Celltyping#123]
https://github.com/neurogenomics/MAGMA_Celltyping/blob/8cb235fb495a467fb825819a76b2f154d3840146/R/magma_tileplot.r#L60

Maybe set n = dim(results)[1] / length(unique(results$GCOV_FILE))

?

**Comment by AMCalejandro** [comment]
If I am understanding correctly, looking at the beginning of the magma_tileplot.R function, the results argument should be a data frame having results from at least two different association tests.
Therefore, if you calculate q as you are suggesting, we would be bonferroni adjusting across studies, but maybe it is best to correct for multiple testing per study independently?

**Comment by bschilder** [comment]
Actually, our thinking was that it was most appropriate to apply multiple testing across all tests that were performed, regardless of what GWAS they come from (which I assume it what you mean by "study"). For example, if you run MAGMA.Celltyping on 100 GWAS and only apply multiple testing correction within each GWAS, you would be undercorrecting for the number of tests that you actually performed.
