### ISSUE TITLE
Likely bug if dendro is set to Null

### ISSUE THREAD

**Issue by AMCalejandro** [neurogenomics/MAGMA_Celltyping#127]
https://github.com/neurogenomics/MAGMA_Celltyping/blob/8cb235fb495a467fb825819a76b2f154d3840146/R/plot_celltype_associations.r#L163

I think this is likely to fail if I do not want to get a dendogram

**Comment by bschilder** [comment]
This function has been rewritten to make a number of improvements, including avoiding the scenario described here.
Implemented in `MAGMA.Celltyping` v2.0.8
