### ISSUE TITLE
Almost all CTDs are not available

### ISSUE THREAD

**Issue by AMCalejandro** [neurogenomics/MAGMA_Celltyping#131]
Hi,

Most of the CTD datasets are actually not available.....

I wonder if this has an easy fix.... It would be so helpful.

```
ctd_name = c("ctd_AIBS", "ctd_allKI", "ctd_BlueLake2018_FrontalCortexOnly",
    "ctd_BlueLake2018_VisualCortexOnly", "ctd_DivSeq", "ctd_DRONC_human",
    "ctd_DRONC_mouse", "ctd_Saunders", "ctd_Tasic", "ctd_Zeisel2015", "ctd_Zeisel2018",
    "ctd_TabulaMuris", "ctd_Aerts2018", "ctd_Aerts2021", "ctd_Avalos2019",
    "ctd_DescartesHuman", "ctd_DescartesHuman_brain", "ctd_HumanCellLandscape",
    "ctd_Jiang2021", "ctd_Han2022", "ctd_Cao2019", "ctd_Raj2018", "ctd_Raj2018",
    "ctd_Farnsworth2020")

save = lapply(ctd_name, function(x) {
  store = try(MAGMA.Celltyping::get_ctd(x))
})
```

![image](https://user-images.githubusercontent.com/84338703/200832818-5d66d948-adb6-4064-a25c-1a3683fe5cc0.png)

**Comment by AMCalejandro** [comment]
Added a PR to fix

**Comment by AMCalejandro** [comment]
Making sure the user has a personal access token makes download to work

![image](https://user-images.githubusercontent.com/84338703/200855119-5356198c-a0e1-49f8-8406-d658e1021235.png)

**Comment by bschilder** [comment]
This has been a recurrent issue with `piggyback`:
https://github.com/ropensci/piggyback/issues/49

What version of piggyback / R / MAGMA.Celltyping were you using?
 
In the future, please use the ISSUES template when reporting bugs. This will help developers to better assess and fix the issues.
