### ISSUE TITLE
Going through the example

### ISSUE THREAD

**Issue by galvaniquee** [neurogenomics/MAGMA_Celltyping#14]
Hi Nathan,

As I am going through the section **Download summary statistics file & check it is properly formatted**, some of the files are missing such as "https://www.dropbox.com/s/shsiq0brkax886j/20016.assoc.tsv.gz". Could you upload the file for us?

Also, for this snippet in the **Download and prepare the 'Prospective memory' GWAS summary statistics** section:
`gwas_sumstats_path = "~/GWAS_Summary_Statistics/20018.assoc.tsv"
if(!file.exists(gwas_sumstats_path)){
    download.file("https://www.dropbox.com/s/shsiq0brkax886j/20016.assoc.tsv.gz?raw=1",destfile=sprintf("%s.gz",gwas_sumstats_path))
    gunzip(sprintf("%s.gz",gwas_sumstats_path),gwas_sumstats_path)
}`

It seems like you are downloading 20018.assoc.tsv but the dropbox link is pointing towards 20016.assoc.tsv.gz. May I know which one is correct and will be great for you to upload 20018 as well. 

Another thing that I came across is that when I run this code in R:
`ctd = prepare.quantile.groups(ctd,specificity_species="mouse",numberOfBins=40)<br />
print(ctd[[1]]$quantiles[c("Gfap","Dlg4","Aif1"),])<br />
print(table(ctd[[1]]$quantiles[,1]))`

The second line returned NULL and the third line returned < table of extent 0 >. The ctd does contain information and the output from seems to be correct:

`> ctd = prepare.quantile.groups(ctd,specificity_species="mouse",numberOfBins=40)<br />
[1] "Dropping all genes that do not have 1:1 homologs between the two species"
[1] "Species for which homology classes are available:"
[1] "mouse, laboratory"    "human"           "chimpanzee"           "macaque, rhesus". 
[5] "dog, domestic"        "cattle"               "rat"                  "frog, western clawed"
[9] "zebrafish"            "chicken"             
[1] "Selected species: mouse, laboratory"
[1] "Selected species: human"
[1] "Full dataset contains 18981 genes from mouse"
[1] "Full dataset contains 18708 genes from human"
[1] "2231 genes which are present in mouse are deleted in human"
[1] "1958 genes which are present in human are deleted in mouse"
[1] "605 genes are duplicated in mouse"
[1] "220 genes are duplicated in human"
[1] "16468 are shared 1:1 between the two species"`

Let me know and thanks!

**Comment by galvaniquee** [comment]
For the second bug, it seems to be an old issue as mentioned here #11. If i modify 
`print(ctd[[1]]$quantiles[c("Gfap","Dlg4","Aif1"),])`
to 
`print(ctd[[1]]$specificity_quantiles[c("Gfap","Dlg4","Aif1"),])`
the data can be retrieved.

**Comment by NathanSkene** [comment]
Hi, sorry for slow response. Kids off school due to Covid so it's a bit of a battle getting work done.

The issue with the URL's is that Ben Neale deleted all the old GWAS sum stats from his dropbox account and replaced them with new versions (described here: https://www.nealelab.is/uk-biobank). The new versions are formatted differently and I'm not sure they play well with the formating function. 

Any GWAS sumstats can be swapped into their place though, you just need to get them formatted as expected. So they must have:

-  SNP, CHR, BP as first three columns. 
- At least one of these columns: ("Z","OR","BETA","LOG_ODDS","SIGNED_SUMSTAT")
- All of these columns: ("SNP","CHR","BP","P","A1","A2")

**Comment by NathanSkene** [comment]
Hi @galvaniquee. I've fixed the links to sumstats files (and amended the formatting functions and various other things). Thanks for raising this issue. Also fixed the other issue you mentioned with quantiles.
