### ISSUE TITLE
found 0 valid gene covariates, for 0 genes defined in genotype data

### ISSUE THREAD

**Issue by sanderslhc** [neurogenomics/MAGMA_Celltyping#147]
## 1. Bug description

Hi, I want to use this method in other species, like pig or cattle. However, when I created the gene_snp mapping file and celltype file, and inputed them in to the command "MAGMA.Celltyping::celltype_associations_pipeline", there is the error like "found 0 valid gene covariates, for 0 genes defined in genotype data".  I don't know if the MAGMA_Celltyping can be used at other species? Not only at the human and mouse.

### Code 

MAGMA_results <- MAGMA.Celltyping::celltype_associations_pipeline(
  magma_dirs = magma_dirs,
  ctd = ctd,
  ctd_species = "cow",
  ctd_name = "fkg_liver",
  run_linear = TRUE,
  run_top10 = TRUE)

```error
Preparing CellTypeDataset.
Converting to sparse matrix.
Converting to sparse matrix.
Checking CTD: level 1
Checking CTD: level 1
SNP_anno
======= Calculating celltype associations: linear mode =======
Installed MAGMA version: v1.10
Skipping MAGMA installation.
The desired_version of MAGMA is currently installed: v1.10
Using: magma_v1.10
Running MAGMA: Linear mode
Mapping gene symbols in specificity_quantiles matrix to entrez IDs.
Welcome to MAGMA v1.10 (linux)
Using flags:
        --gene-results /faststorage/project/cattle_gtexs/Downstream_analysis/complextraits/MAGMA/fkg/MAGMA_Files/SNP_anno.35UP.10DOWN/SNP_anno.35UP.10DOWN.genes.raw
        --gene-covar /scratch/usertmp/RtmpI0ZypX/file223b3a7ea0d904
        --model direction=pos
        --out /faststorage/project/cattle_gtexs/Downstream_analysis/complextraits/MAGMA/fkg/MAGMA_Files/SNP_anno.35UP.10DOWN/SNP_anno.35UP.10DOWN.level1.fkg_liver_linear.Linear

Start time is 13:29:37, Wednesday 11 Oct 2023

Reading file /faststorage/project/cattle_gtexs/Downstream_analysis/complextraits/MAGMA/fkg/MAGMA_Files/SNP_anno.35UP.10DOWN/SNP_anno.35UP.10DOWN.genes.raw...
        15799 genes read from file
Loading gene-level covariates...
Reading file /scratch/usertmp/RtmpI0ZypX/file223b3a7ea0d904...
        detected 15 variables in file (using all)
        WARNING: discarding variable 'B_cells', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Blood_vascular_endothelial_cells', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Cholangiocytes', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Dendritic_cells', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Hepatocytes', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Kupffer_cells', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Liver_sinusoidal_endothelial_cells', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Myofibroblasts', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Neutrophils', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'NK_cells', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'NK_T_cells', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Plasma_cells', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Proliferative_dendritic_cells', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'T_cells', missing value rate exceeds missingness threshold (0.05)
        WARNING: discarding variable 'Unknown_cells', missing value rate exceeds missingness threshold (0.05)
        found 0 valid gene covariates, for 0 genes defined in genotype data

ERROR - loading gene-level data: no valid gene sets or covariates found in input files

Terminating program.
Reading enrichment results file into R.
Error in file(file, "rt"): cannot open the connection

```

## 3. Session info

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: AlmaLinux 8.8 (Sapphire Caracal)

Matrix products: default
BLAS/LAPACK: /home/holi/miniconda3/envs/R/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.utf-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.utf-8        LC_COLLATE=en_US.utf-8
 [5] LC_MONETARY=en_US.utf-8    LC_MESSAGES=en_US.utf-8
 [7] LC_PAPER=en_US.utf-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.utf-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

```

**Comment by bschilder** [comment]
Could you provide a reproducible example (see the instructions you copied)?

**Comment by bschilder** [comment]
Can you also fill out the Session info section? (it's blank)

**Comment by sanderslhc** [comment]
Thank you. I have pasted the code, error and Session info.

**Comment by bschilder** [comment]
@sanderslhc  I'm afraid this isn't enough for me to help you. a reproducible example includes code that others can copy and paste as-is and reproduce the same results. Please follow the instructions that were included in the Issues template:



## 2. Reproducible example   

### Code 

(Please add the steps to reproduce the bug here. See [here](https://www.r-bloggers.com/2020/10/how-to-make-a-reprex/) for an intro to making a reproducible example (i.e. reprex) and why they're important! __This will help us to help you much faster.__)

```R
# Paste example here

```

### Data

(If possible, upload a small sample of your data so that we can reproduce the bug on our end. If that's not possible, please at least include a screenshot of your data and other relevant details.)

**Comment by sanderslhc** [comment]
Thank you for your quick reply. Actually, about this problem, I have already solved it after I transfered the animal genes to orthologous human genes in the magma output file (SNP_anno.35UP.10DOWN.genes.out). However, I don't know if it is reasonable because I'm not sure if the magma celltyping will use the reference genome. If does, it seems can't be used in other species without their reference genome. This is my question.

**Comment by sanderslhc** [comment]
What I mean is, the single cell data and GWAS data are both from other animals, not human. Does magma celltyping can be used for the data?

**Comment by bschilder** [comment]
we've never run `MAGMA.Celltyping` using non-human GWAS data (only non-human CTDs). so i'm afraid you're in new territory in this regard. 

We don't have plans to evaluate the validity of this approach, but if you'd like to investigate and make a PR you're more than welcome to.

**Comment by bschilder** [comment]
One thought; simply converting both non-human inputs datasets (GWAS and CTD) to human orthologs wouldn't really make sense and I don't recommend this approach because you're arbitrarily subsetting the genes based on their orthologs with a species that isn't even relevant to the analysis (human). 

So I think the short answer is "no, you can't currently use `MAGMA.Celltyping` with non-human GWAS". But if you'd like to write an extension of the package that does this properly, we would be happy to take a look at your PR.

Hope that helps a bit.

**Comment by NathanSkene** [comment]
You would need to get an LD matrix for whatever species was being used. What species would this be? Collaborative cross?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sanderslhc** [comment]
THey are the cattle and pig. Actually, I have LD information within my GWAS data and I use them as input files when I'm running the MAGMA process and get the output file(SNP_anno.35UP.10DOWN.genes.out). I just want to know if the following steps will use the reference genome info? If not, I think maybe I can try the magma celltyping in other species. Thank you.

**Comment by NathanSkene** [comment]
Ah wow, that’s really interesting, would be cool to get it working for agricultural traits! I would have thought that having the LD matrix is the main issue, so if you’ve got that things should be do-able in principle. As Brian says though, there might well be some things that are hardcoded to expect human data. Might be best to take a step-by-step approach to this, e.g.

Try to get it working with plain magma first. Check that you get the magma output files generated, with gene level scores. Check you can then get MAGMA_celltyping to generate the same files, etc.

I don’t think that converting gene names in the magma output file is the way to go. Better to actually get it to use the cattle/pig genes and adapt the software to accept this. Think the code is pretty well commented up, so don’t think it should be too hard to do, and we’d be very happy to pull your changes if you get it sorted.

Would be interested to hear more about what you’re trying to do!

From: Sanders Li ***@***.***>
Date: Thursday, 9 November 2023 at 18:54
To: neurogenomics/MAGMA_Celltyping ***@***.***>
Cc: Skene, Nathan G ***@***.***>, Comment ***@***.***>
Subject: Re: [neurogenomics/MAGMA_Celltyping] found 0 valid gene covariates, for 0 genes defined in genotype data (Issue #147)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



THey are the cattle and pig. Actually, I have LD information within my GWAS data and I use them as input files when I'm running the MAGMA process and get the output file(SNP_anno.35UP.10DOWN.genes.out). I just want to know if the following steps will use the reference genome info? If not, I think maybe I can try the magma celltyping in other species. Thank you.
