### ISSUE TITLE
Magma used in other species

### ISSUE THREAD

**Issue by sanderslhc** [neurogenomics/MAGMA_Celltyping#148]
Hi, I'm using the magma celltyping to deal with my GWAS data, but my data are all from other animals. I'm not sure if the magma celltyping can be used in non-human species. If right, what should I change in the code?

**Comment by bschilder** [comment]
Hi @sanderslhc it looks like you asked something quite similar previously, but I haven't hear a reply back regarding the information i would need to answer your question
https://github.com/neurogenomics/MAGMA_Celltyping/issues/147#issuecomment-1757849673

Could you please reply there?
