### ISSUE TITLE
map_snps_to_genes() and get_ctd() related errors

### ISSUE THREAD

**Issue by ShufenZheng** [neurogenomics/MAGMA_Celltyping#149]
Hi,
  I have encountered two problems. 
(1) With a normal network ,I have been unable to download the magma_v1.10_win.zip file. Because when I use the gmap_snps_to_genes function it displays the following error message::  Error in download.file(magma_url, destfile = destfile)：download from 'https://ctg.cncr.nl/software/MAGMA/prog//magma_v1.10_win.zip' failed. 
(2)  When using ctd <- MAGMA.Celltyping::get_ctd("ctd_allKI")  to import CellType dataset, the following error message occurs: Error in `value[[3L]]()`:! Cannot access release data for repo "neurogenomics/MAGMA_Celltyping". Check that you have provided a `.token` and that the repo is correctly specified. GitHub API error (401): Bad credentials. What should I do to solve these situations above?

**Comment by bschilder** [comment]
@zsf123525 you need to set up your GitHub API token
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
