### ISSUE TITLE
Error in sprintf(">50% of celltypes missing. %s celltypes\n in ctd but %s in results file.\n Did you provide the correct annotLevel?", : 参数数目太少

### ISSUE THREAD

**Issue by hardworkandworkhard** [neurogenomics/MAGMA_Celltyping#151]
Hi,
I am trying to run **MAGMA.Celltyping::celltype_associations_pipeline** with the following code:
`MAGMA_results <- MAGMA.Celltyping::celltype_associations_pipeline(
        magma_dirs = trait_path,
        ctd = ctd,
        ctd_species = "human", 
        ctd_levels = 1,
        ctd_name = "test", 
        run_linear = TRUE, 
        run_top10 = TRUE,
        save_dir = result_path)`
ctd is the output of **MAGMA.Celltyping::get_ctd("ctd_allKI",storage_dir=storage_dir)**
The error I encounter all the time is: **Error in sprintf(">50% of celltypes missing. %s celltypes\n                             in ctd but %s in results file.\n                             Did you provide the correct annotLevel?", : 参数数目太少**, same GWAS summary statistics can generate output by setting the ctd as the output of **MAGMA.Celltyping::get_ctd("ctd_BlueLake2018_FrontalCortexOnly",storage_dir=storage_dir)**. This issue also meet when using ctd established by myself via:
```
ctd_lung <- EWCE::generate_celltype_data(
  exp = lung_list_modify$exp,
  annotLevels = annotLevels,
  groupName = "lung", ##generate file named "ctd_lung.rda" if setting so
  no_cores = 1,
  input_species = "human",
  output_species = "human",
  savePath="E:/move/disk_document/Projects_documents/05.allergic_diseases_mental_disorders/01.allergic_diseases_anxiety/04.MAGMA/MAGMA_celltype_enrichment/single_cell_dataset")
```
Do you have any idea how to solve this issue?

Thanks!!!!!!!
![Uploading error info.jpg…]()

**Comment by lfz-123qweasd** [comment]
I have the same problem!!!!
======= Calculating celltype associations: linear mode =======
Installed MAGMA version: v1.10
Skipping MAGMA installation.
The desired_version of MAGMA is currently installed: v1.10
Using: magma_v1.10
Importing precomputed MAGMA results. magma_cmd and geneCovarFile will be set to NULL.
Reading enrichment results file into R.
Error in sprintf(">50% of celltypes missing. %s celltypes\n                             in ctd but %s in results file.\n                             Did you provide the correct annotLevel?", : 参数数目太少

I have slove the problem by：
MAGMA_results <- MAGMA.Celltyping::celltype_associations_pipeline(
  magma_dirs = magma_dirs,
  ctd = ctd,
  ctd_levels = 1,
  ctd_name = "Zeisel2018", 
  run_linear = TRUE, 
  run_top10 = TRUE)

By this ：https://github.com/neurogenomics/MAGMA_Celltyping/issues/130

**Comment by bschilder** [comment]
@hardworkandworkhard can you please submit the Bug issue template so that I can have the information necessary to assess the problem?

**Comment by bschilder** [comment]
@lfz-123qweasd I can't really help much without a complete bug report. 
https://github.com/neurogenomics/MAGMA_Celltyping/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=

In the meantime, please see the answer to the question in #130
