### ISSUE TITLE
map_snps_to_genes

### ISSUE THREAD

**Issue by ushagogal** [neurogenomics/MAGMA_Celltyping#152]
## 1. I am currently attempting to run the map_snps_to_genes function in R.  In addition, the MAGMA_Celltyping package is not loading in my R session, which could contribute to my error.

This is the command that I put into R. 
map_snps_to_genes(
  path_formatted,
  genome_build = NULL,
  upstream_kb = 35,
  downstream_kb = 10,
  N = NULL,
  duplicate = c("drop", "first", "last", "error"),
  synonym_dup = c("skip", "skip-dup", "drop", "drop-dup", "error"),
  genome_ref_path = NULL,
  population = "eur",
  genes_only = FALSE,
  storage_dir = tools::R_user_dir("MAGMA.Celltyping", which = "cache"),
  force_new = FALSE,
  version = NULL,
  verbose = TRUE
)

### Console output 

```
#Error in map_snps_to_genes(path_formatted, genome_build = NULL, upstream_kb = 35,  : 
  could not find function "map_snps_to_genes"

```

### Expected behaviour   

If working properly, I expect the function to be a genes.raw file  about which SNPs map to which genes based on the provided parameters.

**Comment by Al-Murphy** [comment]
I would say you need to `library(MAGMA.Celltyping)` first or use `MAGMA.Celltyping::map_snps_to_genes`, R doesn't know where to find the function in your current set up
