### ISSUE TITLE
How to use GWAS results from studies not included in this package

### ISSUE THREAD

**Issue by barbareyex** [neurogenomics/MAGMA_Celltyping#153]
Hi,

I want to use a study I downloaded from the GWAS catalog of the EMBL-EBI, but I'm not sure if it's possible and in case it is, how to do it. As far as I know, there is no workflow or information about how to manage these datasets.

Does anyone have any idea about how to do this?

Thanks!

**Comment by Al-Murphy** [comment]
Hi,

Yes this is the exact use case Magma.celltyping was created for. See the vignette for the info you need, specifically here: https://neurogenomics.github.io/MAGMA_Celltyping/articles/MAGMA.Celltyping.html#prepare-data.

We advise formatting your GWAS sumstats with Mungesumstats first (`MungeSumstats::format_sumstats()`) then running the `MAGMA.Celltyping::map_snps_to_genes` function. Then the last step is to run the cell type enrichment analysis: `MAGMA.Celltyping::celltype_associations_pipeline()`.

This is all detailed in the vignette, please read it carefully and have a go using the sample data. 

I'll close this issue for now but if you have any problems with specific function calls feel free to open a new one.

Thanks,
Alan.
