### ISSUE TITLE
Add functions for testing a whole set of traits in one go + multiple correction testing for them + generating plots

### ISSUE THREAD

**Issue by kvshams** [neurogenomics/MAGMA_Celltyping#20]
is it possible to adjust enrichment for multiple traits?

**Comment by bschilder** [comment]
@kvshams I'm afraid it's only one trait at a time currently. The immediate solution to this would to be to write a loop iterating over different traits. This should be much easier in the upcoming version of `MAGMA.Celltyping` where I've wrapped many of the functions into several more manageable functions. Currently being developed on the [*bschilder_dev* branch here](https://github.com/neurogenomics/MAGMA_Celltyping/tree/bschilder_dev) .
