### ISSUE TITLE
Installation Error: package ‘EWCE’ could not be loaded

### ISSUE THREAD

**Issue by prashanthsama1** [neurogenomics/MAGMA_Celltyping#21]
Hi,

I used this package few months back. I didn't have any problem installing or working on it. But recently We updated to R(3.6.0) and I had to install the package again. For some reason, I am getting an error, the error message says package " ‘EWCE’ could not be loaded" but I have EWCE package currently installed and when I try to open it using library(EWCE) it works fine. I do not know why installation of MAGMA_Celltyping is not working. Below attached is the error message:

Note: while installing it also says "Skipping 1 packages not available: XML" but I have the XML package installed already(but the version that supports R 3.6.0). 

Please do let me know if you need any further details.

`> devtools::install_github("nathanskene/MAGMA_Celltyping")
Downloading GitHub repo nathanskene/MAGMA_Celltyping@HEAD
Skipping 1 packages not available: XML
✓  checking for file ‘/home/sama/Desktop/tmp/RtmpnJ0NgC/remotesddfe569d5550/NathanSkene-MAGMA_Celltyping-7300011/DESCRIPTION’ (342ms)
─  preparing ‘MAGMA.Celltyping’:
✓  checking DESCRIPTION meta-information ...
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:38: unexpected section header '\value'
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:41: unexpected section header '\description'
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:44: unexpected section header '\examples'
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:52: unexpected END_OF_INPUT '
   '
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/load.magma.results.file.Rd:19: unknown macro '\item'
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/load.magma.results.file.Rd:21: unknown macro '\item'
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/load.magma.results.file.Rd:23: unknown macro '\item'
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/load.magma.results.file.Rd:25: unknown macro '\item'
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/load.magma.results.file.Rd:27: unexpected section header '\value'
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/load.magma.results.file.Rd:30: unexpected section header '\description'
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/load.magma.results.file.Rd:33: unexpected section header '\examples'
   Warning: /home/sama/Desktop/tmp/Rtmp2l4fnt/Rbuildc94465be3c32/MAGMA.Celltyping/man/load.magma.results.file.Rd:37: unexpected END_OF_INPUT '
   '
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘MAGMA.Celltyping_0.99.0.tar.gz’ (19.6s)
   
Installing package into ‘/home/sama/R/x86_64-redhat-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘MAGMA.Celltyping’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Warning: replacing previous import ‘Matrix::cov2cor’ by ‘stats::cov2cor’ when loading ‘EWCE’
Warning: replacing previous import ‘Matrix::toeplitz’ by ‘stats::toeplitz’ when loading ‘EWCE’
Warning: replacing previous import ‘Matrix::update’ by ‘stats::update’ when loading ‘EWCE’
Warning: replacing previous import ‘Matrix::tail’ by ‘utils::tail’ when loading ‘EWCE’
Warning: replacing previous import ‘Matrix::head’ by ‘utils::head’ when loading ‘EWCE’
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for ‘EWCE’:
 (converted from warning) replacing previous import ‘Matrix::cov2cor’ by ‘stats::cov2cor’ when loading ‘EWCE’
Error: package ‘EWCE’ could not be loaded
Execution halted
ERROR: lazy loading failed for package ‘MAGMA.Celltyping’
* removing ‘/home/sama/R/x86_64-redhat-linux-gnu-library/3.6/MAGMA.Celltyping’
Error: Failed to install 'MAGMA.Celltyping' from GitHub:
  (converted from warning) installation of package ‘/home/sama/Desktop/tmp/RtmpnJ0NgC/fileddfe41b693a0/MAGMA.Celltyping_0.99.0.tar.gz’ had non-zero exit status`

Thanks in advance...!!!

**Comment by NathanSkene** [comment]
Hi,

I had this issue with installing EWCE on R3.6 with Travis. Issue is that it
depends on the XML package, the latest version of which now depends on
R4.0. I solved this for the Travis installation by forcing it to install an
old version of XML from source code, then installing EWCE. Let me know if
that solves the problem and how you get on!

**Comment by prashanthsama1** [comment]
Hi,

Thanks for the quick reply. I did the same and EWCE is installed and loading when I load it using library(EWCE). But the main problem is the installation of MAGMA.Celltyping. For some reason while installing MAGMA.Celltyping package it was not able to load EWCE.

**Comment by NathanSkene** [comment]
Gotcha, will need to dig into that. Am on holiday for the week now so will
be a bit delayed doing so.

**Comment by prashanthsama1** [comment]
No problem. Enjoy your holidays...!!!

**Comment by prashanthsama1** [comment]
Hi,
I tried to install the package recently and  there was an update for EWCE package. Once I updated it and tried to install Magma.celltyping package again it worked. So I am closing this issue.

Thank you ..!!!
