### ISSUE TITLE
Magma celltyping on snATAC data

### ISSUE THREAD

**Issue by prashanthsama1** [neurogenomics/MAGMA_Celltyping#22]
Hi,

I have used the package on scRNA data. I am wondering if I can also use sc/snATAC seq data with the package. I believe the package uses the gene names at some point. So, if I want to use ATAC data how can I proceed. Any insights will be helpful.

Thanks in advance...!!!

**Comment by bschilder** [comment]
@prashanthsama1, `MAGMA.Celltyping` does not currently support the use of non scRNA-seq data as cell-type references.
