### ISSUE TITLE
error: magma does not appear to be located on your path

### ISSUE THREAD

**Issue by yabwei** [neurogenomics/MAGMA_Celltyping#23]
Error: package or namespace load failed for 'MAGMA.Celltyping':
 .onLoad failed in loadNamespace() for 'MAGMA.Celltyping', details:
  call: fun(libname, pkgname)
  error: magma does not appear to be located on your path
Please download it from https://ctg.cncr.nl/software/magma
The executable should then be copied to /usr/local/bin

Hi, 
I am trying to install MAGMA.Celltyping  to R windows version. I have magma downloaded for windows version too.
But I don't think windows has /usr/local/bin
Could you help modify the script so that the package can also be installed in windows machine ?
Thank you so much.

**Comment by SarahMarzi** [comment]
Hi Nathan,

I also get the same error message on Mac OS, despite having copied the magma executable into the required path "/usr/local/bin". Any suggestions?

Thanks!

Sarah

**Comment by kvshams** [comment]
Try `/usr/bin/` it works for me!

**Comment by SarahMarzi** [comment]
Thanks for the suggestion, but current Mac OS seems adamant in not letting me add anything to /usr/bin (in fact anywhere in /usr but /usr/local and subfolders) - tried to sudo coerce and all...

**Comment by NathanSkene** [comment]
Put it into '/usr/local/bin/magma'

**Comment by NathanSkene** [comment]
Ah, had only read the last message in the thread :-)

*Yabwei: *I don't have a windows machine & travisCI doesn't really handle
Windows so can't do any testing for that. All you've really got to do is
get the executable running from your path though.

*Sarah: *If you've copied it to /usr/local/bin it's surprising it doesn't
work. If you type 'echo $PATH' at terminal is '/usr/local/bin' on there?
