### ISSUE TITLE
The genomeLocFile now directs to /path/to/MAGMA.Celltyping/data//NCBI*

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/MAGMA_Celltyping#26]
**Sent by Mitchell:**

While running some analyses in MAGMA.Celltyping v1.08, I came across something that I believe is a minor bug. 

It's in the function map.snps.to.genes(), under the section

# Determine which genome build it uses & get path to gene loc file
genome_build = get_genomebuild_for_sumstats(path_formatted)
gene_loc_dir = sprintf("%s/data/",system.file(package="MAGMA.Celltyping"))
if(genome_build == "GRCh37"){genomeLocFile=sprintf("%s/NCBI37.3.gene.loc",gene_loc_dir)}
if(genome_build == "GRCh38"){genomeLocFile=sprintf("%s/NCBI38.gene.loc",gene_loc_dir)}

The genomeLocFile now directs to /path/to/MAGMA.Celltyping/data//NCBI*
Besides the double slashes, the file is actually located in /path/to/MAGMA.Celltyping/extdata/NCBI*

**Comment by bschilder** [comment]
This is now implemented in a way that allows some genome build synonyms, and downloads the appropriate NCBI file via piggyback (to reduce package size and thus improve speed of the overall package). #85
