### ISSUE TITLE
`Error in if (genome_build == "GRCh37") { : argument is of length zero`

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MAGMA_Celltyping#28]
When mapping SNPs to gene with the example GWAS sum stats, I run across the following error message.
```r
genesOutPath <- MAGMA.Celltyping::map.snps.to.genes(gwas_sumstats_path,
                                                    genome_ref_path=genome_ref_path,
                                                    N = 117131)
```
```
[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
Error in if (genome_build == "GRCh37") { : argument is of length zero
```

Not sure if this is relevant, but during the `format_sumstats_for_magma()` step I selected `1 for GRCh37`.

**Comment by NathanSkene** [comment]
Looks like you have no SNP column in the sumstats. Can you send the first few lines of your sumstats file?

**Comment by bschilder** [comment]
I just used the example summary stats, which has a column called "variants"

**Comment by NathanSkene** [comment]
The sum stats file has got to be munged to have the required columns. The `format_sumstats_for_magma` function is supposed to help do this, but given the wild variance in what goes into a sumstats file it can't handle everything. In those instances, the file just needs to be hacked manually to have appropriate columns. Did you get format_sumstats_for_magma working?

**Comment by bschilder** [comment]
Yeah, this was after running `format_sumstats_for_magma`, which tried to infer SNP names from CHR/POS. I've basically just been following the readme example line by line

**Comment by NathanSkene** [comment]
It's been a constant moving target trying to get the tutorial working. I get it working, then the sumstats get moved. And there arn't that many sumstats you can directly link to and download, hence the use of Ben Neale's but they get the location and file structure shifting every once in a while. Need to find one that I can get permission to put onto Zenodo so it's got a permanent location.

Can you look into where the `format_sumstats_for_magma` function is going wrong, fix it and push the fix?

Criteria are that the output file should have:
    SNP, CHR, BP as first three columns.
    It has at least one of these columns: (“Z”,“OR”,“BETA”,“LOG_ODDS”,“SIGNED_SUMSTAT”)
    It has all of these columns: (“SNP”,“CHR”,“BP”,“P”,“A1”,“A2”)

Alternatively, try using the PGC cross-disorder schiz sumstats, as they've got a simpler structure.

**Comment by bschilder** [comment]
Sure, happy to! I can get started as soon as your make me a collaborator

**Comment by NathanSkene** [comment]
You can make a pull request already as it's a public repo, but adding you now

**Comment by NathanSkene** [comment]
Added!

**Comment by bschilder** [comment]
Thanks!

Ok, so I think i see what's going on. When I run the following
```r
col_headers <- MAGMA.Celltyping::format_sumstats_for_magma(path = gwas_sumstats_path)
```
`col_headers` is actually the path to the processed summary stats, which automatically is stored here in this tmp file. Looking at the munging code, it looks like once upon a time column headers were indeed returned (`col_headers = strsplit(rows_of_data[1],"\t")[[1]]`), but it instead now return the tmp dir: 
`"/var/folders/zq/h7mtybc533b1qzkys_ttgpth0000gn/T//Rtmp29HWSq/file15bd87b3b9d7c"`

Given this, I tried supplying the `col_headers` (aka `tmp`) variable here:
```r
genesOutPath <- MAGMA.Celltyping::map.snps.to.genes(col_headers,
                                                    genome_ref_path=genome_ref_path,
                                                    N = 117131)
```

These successfully avoids the `Error in if (genome_build == "GRCh37") { : argument is of length zero` issue, but seems to get hung up on a new one:
```
[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
[1] "GWAS Sumstats appear to come from genome build: GRCh37"
Welcome to MAGMA v1.08a (mac)
Using flags:
	--annotate window=10,1.5
	--snp-loc /var/folders/zq/h7mtybc533b1qzkys_ttgpth0000gn/T//Rtmp29HWSq/file15bd87b3b9d7c
	--gene-loc /Library/Frameworks/R.framework/Versions/3.6/Resources/library/MAGMA.Celltyping/data//NCBI37.3.gene.loc
	--out /var/folders/zq/h7mtybc533b1qzkys_ttgpth0000gn/T//Rtmp29HWSq/MAGMA_Files/file15bd87b3b9d7c.10UP.1.5DOWN/file15bd87b3b9d7c.10UP.1.5DOWN

Start time is 17:23:50, Friday 27 Nov 2020


ERROR - parsing arguments: file '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/MAGMA.Celltyping/data//NCBI37.3.gene.loc' specified in --gene-loc does not exist or is not a file.

Terminating program.
Welcome to MAGMA v1.08a (mac)
Using flags:
	--bfile /Users/schilder/Desktop/model_celltype_conservation/raw_data/MAGMA/g1000_eur/g1000_eur
	--pval /var/folders/zq/h7mtybc533b1qzkys_ttgpth0000gn/T//Rtmp29HWSq/file15bd87b3b9d7c N=117131
	--gene-annot /var/folders/zq/h7mtybc533b1qzkys_ttgpth0000gn/T//Rtmp29HWSq/MAGMA_Files/file15bd87b3b9d7c.10UP.1.5DOWN/file15bd87b3b9d7c.10UP.1.5DOWN.genes.annot
	--out /var/folders/zq/h7mtybc533b1qzkys_ttgpth0000gn/T//Rtmp29HWSq/MAGMA_Files/file15bd87b3b9d7c.10UP.1.5DOWN/file15bd87b3b9d7c.10UP.1.5DOWN

Start time is 17:23:50, Friday 27 Nov 2020


ERROR - parsing arguments: file '/var/folders/zq/h7mtybc533b1qzkys_ttgpth0000gn/T//Rtmp29HWSq/MAGMA_Files/file15bd87b3b9d7c.10UP.1.5DOWN/file15bd87b3b9d7c.10UP.1.5DOWN.genes.annot' specified in --gene-annot does not exist or is not a file.

Terminating program.
```

So it seems that MAGMA can't find `--gene-annot /var/folders/zq/h7mtybc533b1qzkys_ttgpth0000gn/T//Rtmp29HWSq/MAGMA_Files/file15bd87b3b9d7c.10UP.1.5DOWN/file15bd87b3b9d7c.10UP.1.5DOWN.genes.annot`. 

Not sure what this is, but i just checked and this *.genes.annot files does indeed not exist in this tmp folder. Will have to investigate a bit further to figure out why.

**Comment by bschilder** [comment]
Also just noticed that this error occurs first, which might be the root cause.
```
ERROR - parsing arguments: file '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/MAGMA.Celltyping/data//NCBI37.3.gene.loc' specified in --gene-loc does not exist or is not a file.
```

I just dug around the MAGMA.Celltyping package files and it appears these *gene.loc files were moved to a different folder at some point:
`ls -lah /Library/Frameworks/R.framework/Versions/3.6/Resources/library/MAGMA.Celltyping/extdata/`
```
drwxrwxr-x   6 schilder  admin   192B 25 Nov 15:10 .
drwxrwxr-x  11 schilder  admin   352B 25 Nov 15:10 ..
-rw-rw-r--   1 schilder  admin   990B 25 Nov 15:10 Magma_Column_headers.csv
-rw-rw-r--   1 schilder  admin   651K 25 Nov 15:10 NCBI36.3.gene.loc
-rwxrwxr-x   1 schilder  admin   663K 25 Nov 15:10 NCBI37.3.gene.loc
-rw-rw-r--   1 schilder  admin   694K 25 Nov 15:10 NCBI38.gene.loc
```

**Comment by bschilder** [comment]
That was it! Indeed, after copying the`NCBI37.3.gene.loc` file where it was expected to be makes the whole `map.snps.to.genes()` function run smoothly. :) 
```
scp /Library/Frameworks/R.framework/Versions/3.6/Resources/library/MAGMA.Celltyping/extdata/NCBI37.3.gene.loc /Library/Frameworks/R.framework/Versions/3.6/Resources/library/MAGMA.Celltyping/data
```

So I'm going to move all the `inst/extdata/*.gene.loc` files to `data/` and this should do the trick.

I'll also update the README tutorial to reflect the changes to the output of `format_sumstats_for_magma()`

**Comment by NathanSkene** [comment]
Great. Were you running this on linux?

The move to inst/extdat was a recent change to get the package in compliance with devtools::check() requirements (I really want the checks completing so that travis can be setup to make merging changes easier). So ideally the files should go back to inst/extdata, then figure out what causes the package to crash when they are located there. Is the '/data/' path encoded somewhere? Can that just be switched to 'inst/extdata/'?

I assume that it was working with them there when I pulled the change into master, so perhaps it's a mac/linux thing, or related to me having previously intalled versions of the package.

Best to make changes like this as a in a branch, then make a pull request rather than pushing direct to master, so we can figure these things out there. I've broken the master branch a few times before and generally wind up with confused emails from users a few days later.

**Comment by bschilder** [comment]
I actually was running it locally on my Mac just to troubleshoot. Will try on linux next.

Yeah, it def complains that the wrong file type is in `data/`, but I put it there bc it was the easiest way to get things running without accidentally screwing everything else up. I'll have to take a closer look to figure out a long-term solution with `extdata/`.

Very good point about branching, I'll do that for any future changes.

**Comment by bschilder** [comment]
For posterity, my dev branch is here:
https://github.com/NathanSkene/MAGMA_Celltyping/tree/bschilder_dev
