### ISSUE TITLE
Add R function to help install magma command line tool

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MAGMA_Celltyping#29]
I've just added a new function `install_magma()` to try and help users install the magma command line tool. 
@NathanSkene if you could test it out and make sure it works for you we can add it to the README.

**Comment by NathanSkene** [comment]
Thanks, good idea! Can't see where the function is?

**Comment by bschilder** [comment]
Just created a new branch here. The function is `install_magma.R`

https://github.com/NathanSkene/MAGMA_Celltyping/tree/bschilder_dev

**Comment by bschilder** [comment]
Getting close. Now added a function that detects where the user actually have write permissions to, and installing there.

**Comment by bschilder** [comment]
Just tested it out by installing on the Threadripper workstation. Seems to work!!

[Upon loading](https://github.com/neurogenomics/MAGMA_Celltyping/blob/bschilder_dev/R/zzz.R), `MAGMA.Celltyping` now automatically installs MAGMA by doing the following:
1. Checks whether MAGMA is already installed. if so, it tells you which version, and whether it's the latest. You can always use the new exported [`magma_install`](https://github.com/neurogenomics/MAGMA_Celltyping/blob/bschilder_dev/R/magma_install.R) function to upgrade to the newest version if you like.
2. If MAGMA is not installed, it proceeds to [check which versions are available in their archives](https://github.com/neurogenomics/MAGMA_Celltyping/blob/bschilder_dev/R/magma_links.R), and chooses the latest release to install.
3. [Identifies the best place to install MAGMA,](https://github.com/neurogenomics/MAGMA_Celltyping/blob/bschilder_dev/R/find_install_dir.R) dependencies on which folders the user has write permissions for.
4. [Creates a symlink to the MAGMA executable](https://github.com/neurogenomics/MAGMA_Celltyping/blob/bschilder_dev/R/magma_create_symlink.R) (or simply copies it into the main `bin` directory, depending on which installation path was chosen in the previous step)
5. [Run checks to confirm that MAGMA is working as expected](https://github.com/neurogenomics/MAGMA_Celltyping/blob/bschilder_dev/R/magma_installation_successful.R) and reports the installed version to the user.
6. If this final check fails bc MAGMA was not installed (or the symlink is not working for whatever reason),[ step-by-step instructions on how to manually install MAGMA ](https://github.com/neurogenomics/MAGMA_Celltyping/blob/bschilder_dev/R/magma_installation_info.R)will be printed to the user.
