### ISSUE TITLE
Add interface to IEU Open GWAS R Package as alternative to formatting sumstats etc

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/MAGMA_Celltyping#31]
Various R packages already do this: [IEU OpenGWAS API](https://gwas-api.mrcieu.ac.uk/)

[R interface to the IEU GWAS database API • ieugwasr](https://mrcieu.github.io/ieugwasr/)

**Comment by NathanSkene** [comment]
It's not immediately clear how it can be used to obtain full summary stats, the vignette just discusses 

([GWAS Glue uses it to run LDSC](https://mrcieu.github.io/gwasglue/)) so it must be possible for it to pull whole GWAS summary statistics

**Comment by bschilder** [comment]
Direct API-access to all public OpenGWAS datasets is now available via [`MungeSumstats::import_sumstats`](https://neurogenomics.github.io/MungeSumstats/reference/import_sumstats.html).
https://github.com/neurogenomics/MungeSumstats/issues/9 

I've updated the vignettes in `MAGMA.Celltyping` to demonstrate this capability.
