### ISSUE TITLE
enrichment_p or P?

### ISSUE THREAD

**Issue by zhanglab2008** [neurogenomics/MAGMA_Celltyping#39]
Thanks Nathan for sharing the codes! I was able to successfully run the pipeline. However, I am confused about the output from LDSC. Would you use the enrichment_p or the P (1-pnorm(Coefficient_z-score) to assess if a cell type has significant association with the trait?
Many thanks!
Zhang

**Comment by bschilder** [comment]
@zhanglab2008, I don't believe LDSC is currently part of this pipeline. @NathanSkene correct me if I'm wrong.
