### ISSUE TITLE
How to build the single-cell expression matrix

### ISSUE THREAD

**Issue by xiangboyulan** [neurogenomics/MAGMA_Celltyping#4]
Dear Nathan,

I read the example about MAGMA_celltyping, I can not understand how to build the expression matrix (such as ctd in your data). I only use one brain region, and do not need to merge. Could you give some advice to me? Thank you so much!

Best,

Bo

**Comment by NathanSkene** [comment]
Hi Bo,

The tutorial for building the ctd is associated with the EWCE package:

https://github.com/NathanSkene/EWCE/

Hope that helps,

Nathan
