### ISSUE TITLE
Add functions to find intersection of genes with high genetic load + cell type specificity (similar to approach used in Parkinsons nature genetics paper)

### ISSUE THREAD

**Issue by williamlam314** [neurogenomics/MAGMA_Celltyping#40]
Dear Nathan,

Thank you for sharing your code.  I am an iBSC student at UCL and have been using this pipeline to identify association between different liver disease and cell types and have got some interesting data.  I was wondering whether it would be possible to obtain the intersection of genes between the gwas sum stats and the cell type data, in essence the genes driving the association?

**Comment by NathanSkene** [comment]
In principle you can get it by looking at the scores associated with each
gene in the MAGMA file. I've never found an approach for doing this that I
consider particularly meaningful though.

**Comment by williamlam314** [comment]
Dear Nathan,

Thank you for your response.  I was wondering if you might have an idea therefore on how, having identified a cell type significantly associated with disease, one should then prioritise targets to investigate for functional relevance in that cell type?

**Comment by bschilder** [comment]
Hi @williamlam314 this is now implemented in the function `MAGMA.Celltyping::get_driver_genes`. Hope it answers your questions!
