### ISSUE TITLE
"There is no SNP column found within the data." Error in load(filePath) : empty (zero-byte) input file

### ISSUE THREAD

**Issue by acburns** [neurogenomics/MAGMA_Celltyping#41]
Hi Nathan,

Thank you for this excellent package. 

I am running into an issue whereby after running the formatting function and attempting to map the SNPs from the GWAS to the genes it is giving me the following error:

There is no N column within the sumstats file. What is the N value for this GWAS?280897
[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
Error in load(filePath) : empty (zero-byte) input file

I am using the most up-to-date R 4.1 and packages for MAGMA.Celltyping and EWCE

Reards,

Angus

**Comment by NathanSkene** [comment]
Hi,

Did you use our new MungeSumstats package for formatting or the old version
of the function?

Could you share the header of the file you are formatting, or link to
download it from?

**Comment by acburns** [comment]
Hi Nathan,

I used the old one but have since tried the MungeSumstats package and am still getting the same error where it will ask me for the N and then state:
"[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
Error in load(filePath) : empty (zero-byte) input file"

I should also note that this also happens with I run the old command format_sumstats_for_magma on the sample dataset provided in the tutorial.
"[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
Which genome build is the data from? 1 for GRCh37, 2 for GRCh38... 1
[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
Error in load(filePath) : empty (zero-byte) input file"

The header for my file is below: 
![image](https://user-images.githubusercontent.com/26035086/124220363-1d8bf200-db41-11eb-82e5-ca8f379d414f.png)

Regards,
Angus

**Comment by acburns** [comment]
Apologies the above screenshot shows an empty A2 column which isn't correct - have successfully run the mungesumstats function and the map.snps.to.genes function still gives the error: [1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
Error in load(filePath) : empty (zero-byte) input file"

**Comment by Al-Murphy** [comment]
Hi,

That error message seems odd considering you do have a SNP column in your data. Our Bioconductor MungeSumstats package should be able to handle that. Could you share a link to download the dataset so we can investigate further? Even a subset of the full dataset which still gives the same error would be suitable.

Thanks,
Alan.

**Comment by acburns** [comment]
Hi Al, 

Is there an email I can send it to? 

This issue is coming up after having successfully run the MungeSumStats package unfortunately. 

![image](https://user-images.githubusercontent.com/26035086/124420904-c0dc4180-dda3-11eb-9985-6832e6ff1be1.png)


This is the relevant code - after running the map.snps.to.genes function I get the above error. 

Regards,

Angus

**Comment by Al-Murphy** [comment]
Hi Angus,

Thanks for that, you can send it to a.murphy@imperial.ac.uk

Alan.

**Comment by NathanSkene** [comment]
You can upload some files directly to guthub issues (zip it first). Or
upload Google drive link? Or send the later to ***@***.***

**Comment by acburns** [comment]
Hi both,

I put some test subset files from the GWAS in a google doc folder - https://drive.google.com/drive/folders/1uwiW_nOkmZQy_fXlny1oOV4OHMOara5b?usp=sharing

One is a .txt file before formatting and the other is what came out of the successful formatting step which still gives the above error.

**Comment by Al-Murphy** [comment]
Hi,

I've downloaded these files and ran the raw file through MungeSumstats and got the same output as you noted. Can you please send on the MAGMA_Celltyping code you used to get the error? My call to `map.snps.to.genes` doesn't produce an error but I do get the message:

[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."

Which shouldn't be occurring but we can fix on our end.

**Comment by acburns** [comment]
Hi Al, 

I've added a .txt file to the drive with the simple code (basically just as the tutorial) 

Glad to hear you got the same issue - perhaps the error on my end is resultant of the package not successfully reading in the data, therefore giving a zero-byte error.

**Comment by Al-Murphy** [comment]
Thanks for this, could you also copy/paste the console print out you get after running:
```
genesOutPath = map.snps.to.genes(path_formatted=gwas_sumstats_path_formatted,
                                 genome_ref_path=genome_ref_path)

```
to this text file? I don't get an error when I run this line so like you said it could be a local issue.

**Comment by bschilder** [comment]
I also experienced this with data from Open GWAS after formatting it with`MungeSumstats`: [Kunkle2019 AD GWAS](https://gwas.mrcieu.ac.uk/datasets/ieu-b-2/) 

I looked into the code and it appears that `load_snp_loc_data()` is called when determining the genome build in `get_genomebuild_for_sumstats()`. `load_snp_loc_data()` prints the message *"There is no SNP column found within the data. It must be inferred from CHR and BP information"* regardless of whether this is actually true or not. I suspect this function was built for RSID mapping originally and then reused later for genome build inference, without noticing what it prints out. I've moved this line elsewhere to ensure it only gets called only when the SNP column is actually missing. 

Regardless, think of ways to avoid or speed up the `load_snp_loc_data()` step will save users at least several to ten minutes  every time they run `map.snps.to.genes()`. Some ideas: 

1. Only load `SNP_LOC_DATA` once. Currently, if RSIDS actually do have to be mapped this would mean it gets loaded twice , substantially adding to the total run time. 

2. Save `SNP_LOC_DATA` in a format that reads into memory more quickly. e g [qs](https://github.com/traversc/qs).

3. Save `SNP_LOC_DATA` in a format that can be queried to pull out only relevant portions when needed ([tabix](http://www.htslib.org/doc/tabix.html) vcf/tsv). This avoids loading the entire file into memory at once.

4. Find a more efficient genome build inference method.


Once implemented, i'll push these fixes/upgrades into my [bschilder_dev](https://github.com/NathanSkene/MAGMA_Celltyping/tree/bschilder_dev) branch and then merge into master once it's ready.

**Comment by bschilder** [comment]
In fact, the first thing `get_genomebuild_for_sumstats()` does is subsample the data. Why not just include it as a dataset built into the package? (it's only 1.1Mb)?
```R
sub_SNP_LOC_DATA = SNP_LOC_DATA[sample(1:dim(SNP_LOC_DATA)[1],100000),]
```

another option:

5. Save and read as a compressed tsv with data.table. 

```R
 filePath = sprintf("%s/MAGMA.Celltyping/data/SNP_LOC_DATA.rda",.libPaths()[1])
data.table::fwrite(SNP_LOC_DATA,"~/Desktop/SNP_LOC_DATA.tsv.gz", sep="\t")
 SNP_LOC_DATA2 <- data.table::fread("~/Desktop/SNP_LOC_DATA.tsv.gz")

```

**Comment by Al-Murphy** [comment]
Hey @bschilder, yep same conclusion I came to! Good to hear your branch has changed this! It would be good if you at least add the check to the `load_snp_loc_data()` that doesn't reinstall if the file is already present in the expected folder to your branch too?

@acburns can you please confirm that there is no actual error when you run:

```
genesOutPath = map.snps.to.genes(path_formatted=gwas_sumstats_path_formatted,
                                 genome_ref_path=genome_ref_path)
```

but instead just the message:
```
[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
```

so we can close this issue.

Thanks,
Alan.

**Comment by NathanSkene** [comment]
Does sound like a better idea to set it up this way with a
separate downsampled version. Would be great if you could implement! Might
be worth pulling out the "which genome build?" code into a
separate function/package (does any equivalent already exist?).

**Comment by bschilder** [comment]
@NathanSkene I actually went ahead and implemented the downsampled version in my branch as a built-in dataset. Much faster now! 

For instances where the full SNP_LOC_DATA file is needed, an alternative to downloading the Figshare file is using a strategy like @Al-Murphy  has implemented in [MungeSumstats: using the BSgenome 
Bioc packages to get the SNP loc data](https://github.com/neurogenomics/MungeSumstats/blob/master/R/load_snp_loc_data.R). This means: 

- We don't have to worry about providing data via Figshare
- The data is always available (doesn't have to be downloaded) so long as the respective BSgenome packages are installed
- The reference datasets always will be up to date (so long as the BSgenome packages are maintained)

**Comment by Al-Murphy** [comment]
@bschilder we could add this as a function to MungeSumstats rather than the people inputting their genome build? It would require having both the BS Genome GRCH37 and GRCH38 packages downloaded by the user which would take some time but is a once off. It would be a nice feature to have there anyway? Then it could be used in MAGMA_celltyping too?

**Comment by bschilder** [comment]
That actually makes quite a bit of sense, @Al-Murphy. MungeSumstats really is meant to replace MAGMA_Celltyping's`format_sumstats_for_magma` function anyways, so it would be good to include it as a dep (or at least a Suggest).

**Comment by NathanSkene** [comment]
Seems like a good suggestion. Am I right that the bsGenome packages are
considerably larger than the SNP_LOC_DATA though?

**Comment by Al-Murphy** [comment]
No it's a package per SNP Loc dataset, for example
 [BSgenome.Hsapiens.NCBI.GRCh38](https://bioconductor.org/packages/release/data/annotation/html/BSgenome.Hsapiens.NCBI.GRCh38.html)

They have been set up to load very quickly too so doesn't take considerable extra runtime.

**Comment by acburns** [comment]
Hi Al and others,

Al, unfortunately I still get the error described above and reprinted below:
[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
Error in load(filePath) : empty (zero-byte) input file

You are right, perhaps this suggests a local issue but I am not sure what this could be as the mungesumstats works just fine. 

As I mentioned before, I am using R 4.1.0, MungeSumstats_1.0.1, EWCE_1.1.1, MAGMA.Celltyping_1.0.0, ewceData_1.1.0. 

Would the changes made by @bschilder perhaps help?

Regards,

Angus

**Comment by acburns** [comment]
I should also note that I also have the same error as the most recent issue opened here relating to the prepare.quantile.groups function:

"ctd = prepare.quantile.groups(ctd,specificity_species="mouse",numberOfBins=40)
[1] "Dropping all genes that do not have 1:1 homologs between the two species"
[1] "Species for which homology classes are available:"
character(0)
[1] "Available species options:"
[1] all    simple
<0 rows> (or 0-length row.names)"

Perhaps the two errors are connected and may help us track down the issue.

**Comment by Al-Murphy** [comment]
Hi @acburns, 

The changes being made to MAGMA_celltyping have not yet been pushed to the master branch as they are still under development. Your issue may be due to your version of EWCE however. EWCE 1.1.1 is the dev branch of the Bioconductor release (3.14). The EWCE Bioconductor version is not compatible with MAGMA_cellytyping just yet (although it will be in the coming weeks). For now, can you please install the EWCE version from the github repo neurogenomics/EWCE as described in MAGMA_celltyping's vignette:
```
install_github("neurogenomics/EWCE")
```
As mentioned I don't get any error when I run the code with the dataset you provided. Also, this doesn't appear to be related to the other issue you mentioned.

**Comment by acburns** [comment]
Hi All, 

Thanks Al, I took your advice and downgraded EWCE + I decided to install @bschilder branch of MAGMA.Celltyping - this solved the issue! 

I am running into another problem now unfortunately which I can't seem to fix, it appears that when I run magma via MAGMA.Celltyping there is an issue with finding files:

This happens when I run map.snps.to.genes:

[1] "GWAS Sumstats appear to come from genome build: GRCh37"

ERROR - parsing arguments: directory ''C:/Users/angus/Documents/UKB/Paper2/magma_v1.09a_win/MAGMA_Files/MAGMA_bolt_outdoor_light_v2.txt.formatted.10UP.1.5DOWN/' specified in --out does not exist or is not a directory.

Terminating program.

ERROR - parsing arguments: directory ''C:/Users/angus/Documents/UKB/Paper2/magma_v1.09a_win/MAGMA_Files/MAGMA_bolt_outdoor_light_v2.txt.formatted.10UP.1.5DOWN/' specified in --out does not exist or is not a directory.

Terminating program.

I can't understand why this is happening as I am able to run the MAGMA command line tool perfectly fine. 

The only thing I could see potentially being an issue is the double quotes at the start of the string for the location of the file? 

Regards,

Angus

**Comment by Al-Murphy** [comment]
Hi, can you revert to the master branch of MAGMA_celltyping, the other branch is in dev and thus not ready for use. Let us know if your problem persists there.

Thanks,
Alan.

**Comment by acburns** [comment]
Hi Al, 

Yep - now I've reverted to the master branch I am still having this same error relating to the directory. 

Here again the full printout:

[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
[1] "GWAS Sumstats appear to come from genome build: GRCh37"

ERROR - parsing arguments: directory ''C:/Users/angus/Documents/UKB/Paper2/magma_v1.09a_win/MAGMA_Files/MAGMA_bolt_outdoor_light_v2.txt.formatted.10UP.1.5DOWN/' specified in --out does not exist or is not a directory.

Terminating program.

As you can see I am no longer having the zero-byte file issue but instead this path issue. 

Regards,

Angus

**Comment by Al-Murphy** [comment]
Can you send on the code that is producing this error? I assume the directory does in fact exist?:

C:/Users/angus/Documents/UKB/Paper2/magma_v1.09a_win/MAGMA_Files/MAGMA_bolt_outdoor_light_v2.txt.formatted.10UP.1.5DOWN/

**Comment by acburns** [comment]
Hi Al,

Yeah - this folder is automatically created by MAGMA.Celltyping and exists 

The code is:

> genesOutPath = map.snps.to.genes(path_formatted=gwas_sumstats_path,genome_ref_path=genome_ref_path, N=417739)
[1] "There is no SNP column found within the data. It must be inferred from CHR and BP information."
[1] "GWAS Sumstats appear to come from genome build: GRCh37"

ERROR - parsing arguments: directory ''C:/Users/angus/Documents/UKB/Paper2/magma_v1.09a_win/MAGMA_Files/MAGMA_bolt_outdoor_light_v2.txt.formatted.10UP.1.5DOWN/' specified in --out does not exist or is not a directory.

Terminating program.

ERROR - parsing arguments: directory ''C:/Users/angus/Documents/UKB/Paper2/magma_v1.09a_win/MAGMA_Files/MAGMA_bolt_outdoor_light_v2.txt.formatted.10UP.1.5DOWN/' specified in --out does not exist or is not a directory.

Terminating program.

Regards,

Angus

**Comment by Al-Murphy** [comment]
Hi, 

I'm able to run your sample dataset through without error. Can you try using a different computer or try with the docker file for MAGMA_celltyping in the repo. If the issue persists there then we can follow up but for now this could just be an issue with your local machine

Thanks,
Alan.

**Comment by Al-Murphy** [comment]
@acburns closing this for now, feel free to reopen if you replicate the issue on a separate console or better using the docker file.
