### ISSUE TITLE
Confirm that all functions work with the latest version of magma (1.09b) and if not force dependency on older version

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/MAGMA_Celltyping#48]

**Comment by bschilder** [comment]
Been testing with 1.09a and everything seems to be ok.

Only exception was `calculate_conditional_geneset_enrichment`, which doesn't seems to produce the *.set.out* file. This might be bc they merged everything into one file, *.gsa.out*. Though I'll need to get more familiar with these functions and look into the magma docs to be sure.

Added some functions to try to modularise reading in magma files and handle version differences. Can tweak as needed.
https://github.com/neurogenomics/MAGMA_Celltyping/blob/bschilder_dev/R/magma_read_gsa_out.R
https://github.com/neurogenomics/MAGMA_Celltyping/blob/bschilder_dev/R/magma_read_sets_out.R




At very least, my new version of `calculate_conditional_geneset_enrichment` runs without errors!

**Comment by bschilder** [comment]
Created separate Issue here: #78
