### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by alexandruioanvoda** [neurogenomics/MAGMA_Celltyping#6]
Hi! I was installing the latest version on a node, and this error came out (using either `devtools::install_github` and `remotes::install_github`):

> > remotes::install_github("nathanskene/MAGMA_Celltyping") Downloading GitHub repo nathanskene/MAGMA_Celltyping@master These packages have more recent versions available. Which would you like to update?  1:   colorspace (1.4-0     -> 1.4-1    ) [CRAN] 2:   XML        (3.98-1.16 -> 3.98-1.19) [CRAN] 3:   CRAN packages only 4:   All 5:   None  Enter one or more numbers separated by spaces, or an empty line to cancel 1: 5 ✔  checking for file ‘/tmp/RtmpTMiZNJ/remotes14476b11eefb/NathanSkene-MAGMA_Celltyping-bdab1fa/DESCRIPTION’ ... ─  preparing ‘MAGMA.Celltyping’: ✔  checking DESCRIPTION meta-information ...    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:31: unexpected section header '\value'    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:34: unexpected section header '\description'    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:37: unexpected section header '\examples'    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:45: unexpected END_OF_INPUT '    '    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/load.magma.results.file.Rd:13: unknown macro '\item'    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/load.magma.results.file.Rd:15: unknown macro '\item'    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/load.magma.results.file.Rd:17: unknown macro '\item'    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/load.magma.results.file.Rd:19: unknown macro '\item'    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/load.magma.results.file.Rd:21: unexpected section header '\value'    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/load.magma.results.file.Rd:24: unexpected section header '\description'    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/load.magma.results.file.Rd:27: unexpected section header '\examples'    Warning: /tmp/Rtmpm8tgPq/Rbuild188917afa83d/MAGMA.Celltyping/man/load.magma.results.file.Rd:31: unexpected END_OF_INPUT '    ' ─  checking for LF line-endings in source and make files and shell scripts ─  checking for empty or unneeded directories ─  looking to see if a ‘data/datalist’ file should be added    Warning: file ‘ctd_AIBS.rda’ has magic number 'versi'      Use of save versions prior to 2 is deprecated      unable to create a ‘datalist’ file: may need the package to be installed ─  building ‘MAGMA.Celltyping_0.99.0.tar.gz’    Warning: invalid uid value replaced by that for user 'nobody'     Installing package into ‘/gfs/devel/avoda/R/x86_64-pc-linux-gnu-library/3.5’ (as ‘lib’ is unspecified) * installing *source* package ‘MAGMA.Celltyping’ ... ** R ** data *** moving datasets to lazyload DB Warning: file ‘ctd_AIBS.rda’ has magic number 'versi'   Use of save versions prior to 2 is deprecated Error in load(zfile, envir = envir) :    bad restore file magic number (file may be corrupted) -- no data loaded ERROR: lazydata failed for package ‘MAGMA.Celltyping’ * removing ‘/gfs/devel/avoda/R/x86_64-pc-linux-gnu-library/3.5/MAGMA.Celltyping’ Error in i.p(...) :    (converted from warning) installation of package ‘/tmp/RtmpTMiZNJ/file144722b7defb/MAGMA.Celltyping_0.99.0.tar.gz’ had non-zero exit status
> --
>  
> > | >
> >
> 
>

**Comment by alexandruioanvoda** [comment]
And it seems to be specific to this version, as my old fork installs just fine:


> remotes::install_github("alexandruioanvoda/MAGMA_Celltyping-1")
Downloading GitHub repo alexandruioanvoda/MAGMA_Celltyping-1@master
These packages have more recent versions available.
Which would you like to update?

1:   colorspace (1.4-0     -> 1.4-1    ) [CRAN]
2:   XML        (3.98-1.16 -> 3.98-1.19) [CRAN]
3:   CRAN packages only
4:   All
5:   None

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 5
✔  checking for file ‘/tmp/RtmpTMiZNJ/remotes14474bf47e93/alexandruioanvoda-MAGMA_Celltyping-1-017081b/DESCRIPTION’ ...
─  preparing ‘MAGMA.Celltyping’:
✔  checking DESCRIPTION meta-information ...
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:31: unexpected section header '\value'
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:34: unexpected section header '\description'
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:37: unexpected section header '\examples'
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:45: unexpected END_OF_INPUT '
   '
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/load.magma.results.file.Rd:13: unknown macro '\item'
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/load.magma.results.file.Rd:15: unknown macro '\item'
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/load.magma.results.file.Rd:17: unknown macro '\item'
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/load.magma.results.file.Rd:19: unknown macro '\item'
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/load.magma.results.file.Rd:21: unexpected section header '\value'
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/load.magma.results.file.Rd:24: unexpected section header '\description'
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/load.magma.results.file.Rd:27: unexpected section header '\examples'
   Warning: /tmp/RtmpSsM4pX/Rbuild1cf625af0c8/MAGMA.Celltyping/man/load.magma.results.file.Rd:31: unexpected END_OF_INPUT '
   '
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘MAGMA.Celltyping_0.99.0.tar.gz’ (3.4s)
   Warning: invalid uid value replaced by that for user 'nobody'
   
Installing package into ‘/gfs/devel/avoda/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘MAGMA.Celltyping’ ...
** R
** data
*** moving datasets to lazyload DB
Warning: objects ‘ctd’, ‘ctd’, ‘ctd’ are created by more than one data call
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘MAGMA.Celltyping’
Warning: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘MAGMA.Celltyping’
Warning: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘MAGMA.Celltyping’
Warning: replacing previous import ‘cowplot::ggsave’ by ‘ggplot2::ggsave’ when loading ‘MAGMA.Celltyping’
Warning: replacing previous import ‘dplyr::combine’ by ‘gridExtra::combine’ when loading ‘MAGMA.Celltyping’
** help
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:31: unexpected section header '\value'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:34: unexpected section header '\description'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:37: unexpected section header '\examples'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/calculate_celltype_associations.Rd:45: unexpected END_OF_INPUT '
'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/load.magma.results.file.Rd:13: unknown macro '\item'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/load.magma.results.file.Rd:15: unknown macro '\item'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/load.magma.results.file.Rd:17: unknown macro '\item'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/load.magma.results.file.Rd:19: unknown macro '\item'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/load.magma.results.file.Rd:21: unexpected section header '\value'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/load.magma.results.file.Rd:24: unexpected section header '\description'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/load.magma.results.file.Rd:27: unexpected section header '\examples'
Warning: /tmp/RtmpZMfZqT/R.INSTALL1d027b978780/MAGMA.Celltyping/man/load.magma.results.file.Rd:31: unexpected END_OF_INPUT '
'
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘MAGMA.Celltyping’
Warning: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘MAGMA.Celltyping’
Warning: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘MAGMA.Celltyping’
Warning: replacing previous import ‘cowplot::ggsave’ by ‘ggplot2::ggsave’ when loading ‘MAGMA.Celltyping’
Warning: replacing previous import ‘dplyr::combine’ by ‘gridExtra::combine’ when loading ‘MAGMA.Celltyping’
No arguments specified. Please consult manual for usage instructions.

Exiting MAGMA. Goodbye.
* DONE (MAGMA.Celltyping)

**Comment by alexandruioanvoda** [comment]
It looks as if `ctd_AIBS.rda` is saved in a wrong format. See https://stackoverflow.com/a/21505731

**Comment by NathanSkene** [comment]
Hi Alex,

Thanks for letting me know about this. I had tried moving the data files to LFS but apparently install_github is not compatible with repositories which use LFS. I think it's fixed now (works on my computer at least). 

Let me know if you've still got any issues.

Nathan
