### ISSUE TITLE
Missing parameter error

### ISSUE THREAD

**Issue by alexandruioanvoda** [neurogenomics/MAGMA_Celltyping#7]
Was running this:

> library(MAGMA.Celltyping)
> data(ctd_DRONC_human)
> ctd <- ctd_DRONC_human
> rm(ctd_DRONC_human)
> ctd = prepare.quantile.groups(ctd,specificity_species="human",numberOfBins=40)

And got this error:
> > ctd = prepare.quantile.groups(ctd,specificity_species="human",numberOfBins=40)
> Error in apply(ctdIN$specificity, 2, FUN = bin.columns.into.quantiles,  :
>  argument "numberOfBins" is missing, with no default

Apparently it is because of this line, where `numberOfBins` isn't (and should be) passed:
https://github.com/NathanSkene/MAGMA_Celltyping/blob/ddc3c685cffdef9377660389bf87573cefd404dd/R/prepare.quantile.groups.r#L30

**Comment by NathanSkene** [comment]
Fixed, thanks again for reporting and finding the problem!

**Comment by alexandruioanvoda** [comment]
After removing the package, restarting R and reinstalling the package from the master branch, but the error seems to persist:

> > ctd = prepare.quantile.groups(ctd,specificity_species="human",numberOfBins=40)
>Error in apply(ctdIN$specificity, 2, FUN = bin.columns.into.quantiles,  : 
>  argument "numberOfBins" is missing, with no default

Browsed to the line, seems like no commit was pulled there? @NathanSkene
