### ISSUE TITLE
Pass CRAN checks

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MAGMA_Celltyping#83]

**Comment by bschilder** [comment]
First step towards victory!

<img width="548" alt="Screenshot 2021-11-23 at 20 37 22" src="https://user-images.githubusercontent.com/34280215/143155544-f75f38ea-4b89-42fd-bf86-5a6d233fd6ab.png">

## Caveats
- This is on my local machine 
- I've disabled examples/tests for `map_snps_to_genes` bc it's the only function that requires the large 1KG ref files. These take a long time a download and today have been extra slow (timing out even after I set the timeout limit to 5min). As soon as I figure out a way around this, I'll uncomment these tests.
- That said, I can confirm `map_snps_to_genes` is working really smoothly, as it's currently chugging along and processing many different GWAS on the Threadripper atm.
- The one "Note" is actually the startup message that MAGMA was installed. Not sure how to get the CRAN checks to recognize this isn't a problem.

**Comment by NathanSkene** [comment]
Great work!
________________________________
