### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MAGMA_Celltyping#95]
Currently quite low. Made extra tricky since *test-map_snps_to_genes* takes a long time. Not ideal for a unit test, but might be worth un-hashing.
![Screenshot 2022-01-07 at 14 58 20](https://user-images.githubusercontent.com/34280215/148562082-3f40a970-cac8-4567-bb34-696f24fe48c5.png)

**Comment by NathanSkene** [comment]
Somewhat offtopic, but can't we delete the format_sumstats functions now we've got MungeSumstats? That would presumably increase the code coverage

**Comment by bschilder** [comment]
I think that's actually a really good idea @NathanSkene . I was trying to avoid back-compatibility issues, but given that we're bumping to the version to 2.0.0 i think this is an ideal time to completely remove these functions. This will def help to increase coverage.

**Comment by Al-Murphy** [comment]
I don't really agree -  I think making things as easy as possible for a user like telling them that a function is no longer in use is more important than the code coverage percentage. My notes on code coverage was that a lot of functions weren't being tested and secondly that I thought testing should be done to ensure the results from this version are the same as using the old version. I don't think we will be able to or should be aiming to get the code coverage percentage up to a very high percent and should instead focus on what we are actually testing. Plus we could just add a test where these defunct functions are called then they would be covered anyway

**Comment by bschilder** [comment]
> I don't really agree - I think making things as easy as possible for a user like telling them that a function is no longer in use is more important than the code coverage percentage.

You have a point here, it's something I've been going back and forth on. Perhaps worth a brief discussion during lab meeting?

> Plus we could just add a test where these defunct functions are called then they would be covered anyway

I'd agree except that some of these functions introduce the requirement for genome build Bioc packages, which take a while to install. Just something to consider.

**Comment by Al-Murphy** [comment]
>You have a point here, it's something I've been going back and forth on. Perhaps worth a brief discussion during lab meeting?

Sure!

>I'd agree except that some of these functions introduce the requirement for genome build Bioc packages, which take a while to install. Just something to consider.

If you put these packages in the suggests the install time won't count in the R CMD Check time though? - Like the approach we use in MungeSumstats.

**Comment by bschilder** [comment]
> If you put these packages in the suggests the install time won't count in the R CMD Check time though? - Like the approach we use in MungeSumstats.

True! Sorry, that's actually what I meant. But bc my GHA pipeline installs all dev deps (Imports and Suggests) it just takes a bit longer. Not a big deal, just means I have to wait a bit longer to finish each workflow.

**Comment by bschilder** [comment]
Removed code inside deprecated functions, and added unit tests to ensure they throw errors with helpful messages when called: [*test-deprecation.r*](https://github.com/neurogenomics/MAGMA_Celltyping/blob/bschilder_dev/tests/testthat/test-deprecation.r) 

Between this and removing unused functions, test coverage is now >54%. 

![Screenshot 2022-01-24 at 16 40 51](https://user-images.githubusercontent.com/34280215/150825621-9e7592f6-63b2-4fb7-b53d-8503141b4c28.png)

Will continue to bolster this over time.

**Comment by bschilder** [comment]
Coverage now boosted to >76% after fixes and extra unit tests.
![Screenshot 2023-03-02 at 19 33 43](https://user-images.githubusercontent.com/34280215/222533443-9a1793fa-e090-49d1-8731-0947bf8398f1.png)

Full coverage report here:
https://app.codecov.io/gh/neurogenomics/MAGMA_Celltyping/tree/master/R

**Comment by NathanSkene** [comment]
Great job, thank you for doing this!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
