### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by XihanZhang** [neurogenomics/MAGMA_Celltyping#98]
I'm installing MAGMA.Celltyping from R Studio (R version 4.1.1 (2021-08-10)), when I executed the code as below (pasted from the GitHub Readme):
`remotes::install_github("neurogenomics/MAGMA.Celltyping")`
I got an error like below:
```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`neurogenomics`) and repo name (`MAGMA.Celltyping`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```
What's wrong? How do I install this package?

**Comment by bschilder** [comment]
Apologies, that's a mistake on my part when i tried automating the installation instructions in the README.  I'll fix this now.

This is bc the repo name is different from the package name.

Try replacing the . with a _ :
```R
remotes::install_github("neurogenomics/MAGMA_Celltyping")
```

**Comment by XihanZhang** [comment]
Hey thanks! It worked!!

**Comment by zhuojiubanzhong** [comment]
I am installing the MAGMA.celltyping R package with an error, but I don't know what the cause of the error is? It is as follows.


if(!require("remotes")) install.packages("remotes")
remotes::install_github("neurogenomics/MAGMA_Celltyping")

library(MAGMA.Celltyping)


ERROR: lazy loading failed for package 'MAGMA.Celltyping'
* removing 'C:/Users/123/Documents/R/win-library/4.1/MAGMA.Celltyping'
Warning message:
  In i.p(...) :
  installation of package ‘C:/Users/123/AppData/Local/Temp/RtmporbGGH/file29105d932424/MAGMA.Celltyping_2.0.4.tar.gz’ had non-zero exit status
> library(MAGMA.Celltyping)
Error in library(MAGMA.Celltyping) : 
  不存在叫‘MAGMA.Celltyping’这个名字的程辑包

What's wrong? How do I install this package?

**Comment by bschilder** [comment]
Hi @zhuojiubanzhong could you provide a bit more information?

Please see the template for an example of how to report bugs:
https://github.com/neurogenomics/MAGMA_Celltyping/issues/new/choose

At a minimum, I'll need:
- R session info
- all output from the R console when trying to install `MAGMA.Celltyping` (not just the part that shows a warning)
